-- Migration: Advanced Features for Transactions
-- This migration adds enhanced fields to Transactions table and creates optional tables for advanced features

-- Step 1: Add new columns to Transactions table
ALTER TABLE "Transactions"
    ADD COLUMN IF NOT EXISTS "FailureReason" integer NULL,
    ADD COLUMN IF NOT EXISTS "RetryCount" integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "RiskScore" integer NULL,
    ADD COLUMN IF NOT EXISTS "RiskLevel" integer NULL,
    ADD COLUMN IF NOT EXISTS "StatusChangedAt" timestamp with time zone NULL;

-- Step 2: Update existing transactions to have StatusChangedAt = CreatedAt
UPDATE "Transactions"
SET "StatusChangedAt" = "CreatedAt"
WHERE "StatusChangedAt" IS NULL;

-- Step 3: Create indexes for performance
CREATE INDEX IF NOT EXISTS "IX_Transactions_Status_StatusChangedAt" ON "Transactions" ("Status", "StatusChangedAt");
CREATE INDEX IF NOT EXISTS "IX_Transactions_RiskLevel_Status" ON "Transactions" ("RiskLevel", "Status");

-- Step 4: Create MerchantAccounts table (optional)
CREATE TABLE IF NOT EXISTS "MerchantAccounts" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NULL,
    "AccountId" integer NOT NULL,
    "MerchantId" character varying(50) NOT NULL,
    "MerchantName" character varying(200) NOT NULL,
    "QrCodeData" character varying(500) NULL,
    "NfcUrl" character varying(500) NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    CONSTRAINT "PK_MerchantAccounts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MerchantAccounts_Accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES "Accounts" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_MerchantAccounts_MerchantId" ON "MerchantAccounts" ("MerchantId");
CREATE INDEX IF NOT EXISTS "IX_MerchantAccounts_AccountId" ON "MerchantAccounts" ("AccountId");

-- Step 5: Create FraudDetectionRules table (optional)
CREATE TABLE IF NOT EXISTS "FraudDetectionRules" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NULL,
    "RuleName" character varying(100) NOT NULL,
    "RuleType" character varying(50) NOT NULL,
    "ThresholdValue" numeric(18,4) NULL,
    "ThresholdCount" integer NULL,
    "TimeWindow" interval NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    CONSTRAINT "PK_FraudDetectionRules" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_FraudDetectionRules_RuleType" ON "FraudDetectionRules" ("RuleType");
CREATE INDEX IF NOT EXISTS "IX_FraudDetectionRules_IsActive" ON "FraudDetectionRules" ("IsActive");

-- Step 6: Create TransactionStatusHistory table (optional, for audit trail)
CREATE TABLE IF NOT EXISTS "TransactionStatusHistory" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NULL,
    "TransactionId" integer NOT NULL,
    "OldStatus" integer NOT NULL,
    "NewStatus" integer NOT NULL,
    "ChangedAt" timestamp with time zone NOT NULL,
    "ChangedBy" integer NULL,
    "Reason" character varying(500) NULL,
    CONSTRAINT "PK_TransactionStatusHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TransactionStatusHistory_Transactions_TransactionId" FOREIGN KEY ("TransactionId") REFERENCES "Transactions" ("Id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_TransactionStatusHistory_TransactionId" ON "TransactionStatusHistory" ("TransactionId");
CREATE INDEX IF NOT EXISTS "IX_TransactionStatusHistory_ChangedAt" ON "TransactionStatusHistory" ("ChangedAt");

-- Note: The TransactionStatus enum values have been updated:
-- Created = 0, Pending = 1, Sending = 2, Completed = 3, Failed = 4, Expired = 5
-- Existing transactions with Status = 0 (Created) or 1 (Sending) will continue to work.
-- Status = 1 was previously "Sending", but now it's "Pending". 
-- You may need to update existing data if Status = 1 exists:
-- UPDATE "Transactions" SET "Status" = 2 WHERE "Status" = 1; -- Move old Sending to new Sending (2)
